### ISSUE TITLE
Implement support for `let` AQL keyword

### ISSUE THREAD

**Issue by jbrazeau** [ObeoNetwork/M2Doc#183]
Actually if you try to use AQL `let` keyword, you get an unsupported exception (for example : `{ let myvar = 'my string' }`: 
```
java.lang.UnsupportedOperationException: not implemented yet
	at org.obeonetwork.m2doc.parser.BodyTemplateParser.parseLet(BodyTemplateParser.java:352)
	at org.obeonetwork.m2doc.parser.BodyTemplateParser.parseBlock(BodyTemplateParser.java:309)
	at org.obeonetwork.m2doc.parser.BodyTemplateParser.parseRepetition(BodyTemplateParser.java:842)
	at org.obeonetwork.m2doc.parser.BodyTemplateParser.parseBlock(BodyTemplateParser.java:270)
	at org.obeonetwork.m2doc.parser.BodyAbstractParser.parseTemplate(BodyAbstractParser.java:133)
	at org.obeonetwork.m2doc.util.M2DocUtils.parse(M2DocUtils.java:319)
```

**Comment by ylussaud** [comment]
{ m:let myvar = 'my string' }
  ...
{ m:endlet }
