### ISSUE TITLE
Extension '.docx' mandatory in resultFileName, error message is cryptic

### ISSUE THREAD

**Issue by ldelaigue** [ObeoNetwork/M2Doc#220]
I tried to omit the '.docx' in the resultFileName field of a genconf model.

The validation does not complain, but launching the generation causes a worrisome pop-up 'A technical error occurred. Please log a bug (see error log for details)'.
The technical error is the following:
java.lang.reflect.InvocationTargetException
	at org.obeonetwork.m2doc.ide.ui.command.GenerateHandler$1.run(GenerateHandler.java:98)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.lang.IllegalArgumentException: invalid segment portion: null
	at org.eclipse.emf.common.util.URI$Hierarchical.appendFileExtension(URI.java:4245)
	at org.obeonetwork.m2doc.genconf.GenconfToDocumentGenerator.getValidationLogFile(GenconfToDocumentGenerator.java:530)
	at org.obeonetwork.m2doc.genconf.GenconfToDocumentGenerator.validate(GenconfToDocumentGenerator.java:476)
	at org.obeonetwork.m2doc.genconf.GenconfToDocumentGenerator.generate(GenconfToDocumentGenerator.java:202)
	at org.obeonetwork.m2doc.genconf.GenconfToDocumentGenerator.generate(GenconfToDocumentGenerator.java:119)
	at org.obeonetwork.m2doc.ide.ui.command.GenerateHandler$1.run(GenerateHandler.java:87)

There's no way for a use to guess that the problem comes from a missing '.docx' extension in the 'resultFileName' field!

Expected behavior:
- The extension should be automatically added (according to whatever file format will be generated, prbably by reusing the extension of the template file) if it's missing
- If that's not ok, at least the message should be explicit and the validation should ensure that it checks the result file name validity

**Comment by ldelaigue** [comment]
I also think the user guide should be updated to clearly state how the 'result File Name' field should be filled in (path, or name, is it supported to not add the '.docx' extension, etc.)

**Comment by ylussaud** [comment]
see 683c15f835e382ffa5b1e1034126827ea05e30ac
