### ISSUE TITLE
NPE in VariableEditDialog

### ISSUE THREAD

**Issue by ldelaigue** [ObeoNetwork/M2Doc#221]
I get an exception on master when manipulating the variable edit dialog:

java.lang.NullPointerException
	at org.obeonetwork.m2doc.ide.ui.dialog.VariableEditDialog.validate(VariableEditDialog.java:474)
	at org.obeonetwork.m2doc.ide.ui.dialog.VariableEditDialog$3.selectionChanged(VariableEditDialog.java:435)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:158)

I'll submit a pull request to fix this shortly.

**Comment by ylussaud** [comment]
98307ba65534fedd95fb933e54fa93c8d223f55c this commit removes old editors
