### ISSUE TITLE
Exception when inserting word toc

### ISSUE THREAD

**Issue by nlepine** [ObeoNetwork/M2Doc#228]
java.lang.UnsupportedOperationException: Unsupported type of body element : CONTENTCONTROL
	at org.obeonetwork.m2doc.parser.TokenIterator.moveToNextToken(TokenIterator.java:71)
	at org.obeonetwork.m2doc.parser.TokenIterator.hasNext(TokenIterator.java:90)
	at org.obeonetwork.m2doc.parser.TokenProvider.loadNext(TokenProvider.java:85)
	at org.obeonetwork.m2doc.parser.TokenProvider.lookAhead(TokenProvider.java:54)
	at org.obeonetwork.m2doc.parser.M2DocParser.getNextTokenType(M2DocParser.java:186)
	at org.obeonetwork.m2doc.parser.BodyAbstractParser.parseStaticFragment(BodyAbstractParser.java:254)
	at org.obeonetwork.m2doc.parser.M2DocParser.parseBlock(M2DocParser.java:301)
	at org.obeonetwork.m2doc.parser.BodyAbstractParser.parseTemplate(BodyAbstractParser.java:133)
	at org.obeonetwork.m2doc.util.M2DocUtils.parse(M2DocUtils.java:405)

**Comment by nlepine** [comment]
[toc.docx](https://github.com/ObeoNetwork/M2Doc/files/1162682/toc.docx)
