### ISSUE TITLE
NullPointerException with user code

### ISSUE THREAD

**Issue by sthibaudeau** [ObeoNetwork/M2Doc#346]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

M2Doc generation failed with the following NPE :
java.lang.NullPointerException
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.insertUserContent(M2DocEvaluator.java:1307)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseUserDoc(M2DocEvaluator.java:1261)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseUserDoc(M2DocEvaluator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:160)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1216)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1425)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:199)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1216)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseDocumentTemplate(M2DocEvaluator.java:287)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseDocumentTemplate(M2DocEvaluator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:279)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1216)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.generate(M2DocEvaluator.java:276)
	at org.obeonetwork.m2doc.util.M2DocUtils.generate(M2DocUtils.java:694)
	at org.obeonetwork.m2doc.util.M2DocUtils.generate(M2DocUtils.java:652)
	at org.obeonetwork.m2doc.genconf.GenconfUtils.generate(GenconfUtils.java:497)
	at org.obeonetwork.m2doc.genconf.GenconfUtils.generate(GenconfUtils.java:420)
	at org.obeonetwork.m2doc.genconf.editor.command.GenerateHandler$GenerateJob.runInWorkspace(GenerateHandler.java:86)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

## Expected behavior

No NPE.

## Minimal reproduction of the problem with instructions

Bug can be easily reproduced using IS Designer 1.9 and the provided example project.

- Download IS Designer 1.9 https://github.com/ObeoNetwork/InformationSystem/releases
- Import provided zip into workspace [bugIS30.zip](https://github.com/ObeoNetwork/M2Doc/files/3196905/bugIS30.zip)
- Right-click on mpd_template.genconf and select "Generate Documentation"

## Environment

<pre><code>
M2Doc version: 2.0.2.201902011356
Eclipse version: Eclipse Photon
Platform version:  windows 10
IS Designer version : 1.9.0-20190314-1048

</code></pre>

**Comment by ylussaud** [comment]
After looking to the code I found a quick workaround by adding an empty line befor the enduserdoc as in this [mpd_template.docx](https://github.com/ObeoNetwork/M2Doc/files/3247593/mpd_template.docx)

The bug remains and I will create a unit test for it.
