### ISSUE TITLE
Dandling bookmark references in template constructs throw a disconnected exception

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#347]
Unfornunatly to solve this we need to keep track of copied elements in the UserContentRawCopy in order to update BookmarkManager.pendingReferences and BookmarkManager.messagePositions to the copied elements.

This is not easy because we are copying elements at various levels XWPF*, XMLObject, and even serialized XML...

After replacing elements in the BookmarkManager, we should have an error message instead of the XmlValueDisconnectedException.

org.apache.xmlbeans.impl.values.XmlValueDisconnectedException
	at org.apache.xmlbeans.impl.values.XmlObjectBase.check_orphaned(XmlObjectBase.java:1258)
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTPImpl.insertNewR(Unknown Source)
	at org.apache.poi.xwpf.usermodel.XWPFParagraph.insertNewRun(XWPFParagraph.java:1441)
	at org.obeonetwork.m2doc.util.M2DocUtils.insertMessageAfter(M2DocUtils.java:298)
	at org.obeonetwork.m2doc.generator.BookmarkManager.markDanglingReferences(BookmarkManager.java:302)
	at org.obeonetwork.m2doc.util.M2DocUtils.generate(M2DocUtils.java:703)
	at org.obeonetwork.m2doc.tests.AbstractTemplatesTestSuite.prepareoutputAndGenerate(AbstractTemplatesTestSuite.java:462)
	at org.obeonetwork.m2doc.tests.AbstractTemplatesTestSuite.generation(AbstractTemplatesTestSuite.java:369)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by dsryzhov** [comment]
Today have been testing bookmark references from sub-templates. And only after that have understand this issues. It prevets from using boorkmark references from templates. It's very hard to find dangling references after runtime errors. 

During testing with real sub-templates have found quite a lot of isuues when uising sub-templates. I need some time to make test templates and report this issues.

**Comment by dsryzhov** [comment]
workaround for this issues is also to use asLink('generated.docx#'+element.id) but no asBookmarkRef

**Comment by ylussaud** [comment]
This issue is more related to the error message we should see in the generated document. When adding this message an the exception is thrown.
The main difference between asLink('generated.docx#'+element.id) and asBookmarkRef(element.id) is that in the first case no check is may on either or not the referenced bookmark exists. Using asBookmark() and asBookmarkRef() checks for duplicated bookmarks and dangling references.
If you use asLink('generated.docx#'+element.id) in this specific case your reference will be dangling. But yes on other cases if can be a workaround or a way to reference other documents.
