### ISSUE TITLE
m2doc issue with hyperlinks and OLE Objects

### ISSUE THREAD

**Issue by DurianGray** [ObeoNetwork/M2Doc#358]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

Hi I'm using m2doc 2.0.2 in conjunction with capella 1.3.0. Whenever I insert the following fields in the "usercontent" section of the generated document:
* a hyperlink { HYPERLINK "xxx" } 
* an OLE object { EMBED Visio.Drawing.15 }
a broken document is generated.

![2019-08-05 16_56_08-Inbox - jan-erik hein@vras com sg - Outlook](https://user-images.githubusercontent.com/53748965/62453197-6a73bc00-b7a4-11e9-8452-d2b7d66426a8.png)

## Minimal reproduction of the problem with instructions

1. add a userdoc section in Template
2. generate document
3. put in a hyperlink or Visio OLE Obejct in generated document
4. generate again (no error in m2doc, success message in capella)
5. open generated document 

## Environment

<pre><code>
M2Doc version: 2.0.2
Eclipse version: 4.7.3.v20180301-0715
Capella Version: 1.3.0
Platform version:  Windows 

</code></pre>

**Comment by ylussaud** [comment]
There is a [test](https://github.com/ObeoNetwork/M2Doc/tree/master/tests/org.obeonetwork.m2doc.tests/resources/userDoc/userContentWithHyperlink) with an hyperlink in a user doc that has been added on master. So you might want to test the [master update site](https://s3-eu-west-1.amazonaws.com/obeo-m2doc-releases/master/nightly/repository) or [zipped version](https://s3-eu-west-1.amazonaws.com/obeo-m2doc-releases/master/nightly/repository/org.obeonetwork.m2doc.update.zip). Let me know if it solve your issue ?

**Comment by DurianGray** [comment]
Hi ylussaud,
I wasn’t able to test yet. It seems that I have failed to install the nightly build correctly. I am missing capella doc generation utils for example.

!ENTRY org.obeonetwork.m2doc.genconf.editor 4 4 2019-10-07 18:36:17.105
!MESSAGE M2Doc : technical error : Index: 0, Size: 0
!STACK 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
     at java.util.ArrayList.rangeCheck(ArrayList.java:653)
     at java.util.ArrayList.get(ArrayList.java:429)
     at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
     at org.obeonetwork.m2doc.util.M2DocUtils.parseTemplateCustomProperties(M2DocUtils.java:550)
     at org.obeonetwork.m2doc.util.M2DocUtils.parse(M2DocUtils.java:475)
     at org.obeonetwork.m2doc.genconf.GenconfUtils.generate(GenconfUtils.java:484)
     at org.obeonetwork.m2doc.genconf.GenconfUtils.generate(GenconfUtils.java:422)
     at org.obeonetwork.m2doc.genconf.editor.command.GenerateHandler$GenerateJob.runInWorkspace(GenerateHandler.java:86)
     at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by ylussaud** [comment]
I did release the Capella extensions with M2Doc 3.0.0 since M2Doc is still under development. You can probably installe Caeplla extensions and then update M2Doc using the update site.

And I made mistake when closing this issue. The bookmark part is fixed, but the OLE part is only fixed in template constructs. I will reopen this issue and close it when the tests for user doc and the fix will be done. I'm working on it.

**Comment by DurianGray** [comment]
okay, I found my problem. I had a `m:import:org.obeonetwork.capella.m2doc.aql.queries.M2DocGenServices`
in my template's properties, which didn't led to issues before (m2doc 2.0.2). After removing that, I could place hyperlinks in usercontent without word crashing. 

Your hyperlink test example works fine as well. Thank you very much!

OLE objects in user content still lead to broken documents.

**Comment by ylussaud** [comment]
Happy to hear that.

**Comment by DurianGray** [comment]
Okay, I successfully tested OLE Objects in m:usercontent
Thank you and keep up the good work!

**Comment by ylussaud** [comment]
great and thank you for reporting this issue.
