### ISSUE TITLE
NPE while generating the else block of an if with a table in the then block

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#399]
NPE while generating the else block of an if with a table in the then block.

m:template createPropertyRow(level:Integer, property: information::Property)
m:if level = 1
—TABLE ROW—
m:else
TEST
m:endif
m:endtemplate

Produce the following NPE. At some point the generated paragraph is null.

java.lang.NullPointerException at org.obeonetwork.m2doc.generator.M2DocEvaluator.insertRun(M2DocEvaluator.java:411) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseStaticFragment(M2DocEvaluator.java:376) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseStaticFragment(M2DocEvaluator.java:1) at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:239) at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53) at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69) at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1242) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1467) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1) at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:199) at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53) at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69) at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1242) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseConditional(M2DocEvaluator.java:1491) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseConditional(M2DocEvaluator.java:1) at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:134) at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53) at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69) at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1242) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1467) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1) at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:199) at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53) at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69) at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1242) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseRepetition(M2DocEvaluator.java:1226) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseRepetition(M2DocEvaluator.java:1) at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:147) at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53) at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69) at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1242) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1467) at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1) at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:199) at

**Comment by ylussaud** [comment]
A document that can be used as a reproduction case:
[m2doc_issue399_CodeLeadingToNPE.docx](https://github.com/ObeoNetwork/M2Doc/files/5667260/m2doc_issue399_CodeLeadingToNPE.docx)
