### ISSUE TITLE
NPE During doc validation

### ISSUE THREAD

**Issue by RomainGuider** [ObeoNetwork/M2Doc#63]
Here's the stack trace 
java.lang.NullPointerException
	at org.eclipse.acceleo.query.parser.AstValidator.validate(AstValidator.java:871)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseConditionnal(TemplateValidator.java:159)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseConditionnal(TemplateValidator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:94)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseRepetition(TemplateValidator.java:289)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseRepetition(TemplateValidator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:102)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseTemplate(TemplateValidator.java:151)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseTemplate(TemplateValidator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:149)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseDocumentTemplate(TemplateValidator.java:139)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseDocumentTemplate(TemplateValidator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:192)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.TemplateValidator.validate(TemplateValidator.java:130)
	at org.obeonetwork.m2doc.generator.TemplateValidator.validate(TemplateValidator.java:108)
	at org.obeonetwork.m2doc.generator.TemplateValidator.validate(TemplateValidator.java:92)
	at org.obeonetwork.m2doc.api.GenconfToDocumentGenerator.validate(GenconfToDocumentGenerator.java:262)
	at org.obeonetwork.m2doc.api.GenconfToDocumentGenerator.generate(GenconfToDocumentGenerator.java:127)
	at org.obeonetwork.m2doc.api.GenconfToDocumentGenerator.generate(GenconfToDocumentGenerator.java:93)
	at org.obeonetwork.m2doc.ui.command.GenerateHandler.execute(GenerateHandler.java:66)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

**Comment by RomainGuider** [comment]
This may be an AQL issue but here's the report.

**Comment by ylussaud** [comment]
Which version of AQL are you using ?

**Comment by RomainGuider** [comment]
5.0

**Comment by RomainGuider** [comment]
The problem occurs with {m:if} which aren't closed. Here's another stack trace that's obtained with the attached project : 
org.eclipse.e4.core.di.InjectionException: org.eclipse.acceleo.query.runtime.AcceleoQueryValidationException: An internal error occured during validation of a query
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: org.eclipse.acceleo.query.runtime.AcceleoQueryValidationException: An internal error occured during validation of a query
	at org.eclipse.acceleo.query.runtime.impl.ValidationServices.callOrApplyTypes(ValidationServices.java:225)
	at org.eclipse.acceleo.query.parser.AstValidator.caseCall(AstValidator.java:275)
	at org.eclipse.acceleo.query.parser.AstValidator.caseCall(AstValidator.java:1)
	at org.eclipse.acceleo.query.ast.util.AstSwitch.doSwitch(AstSwitch.java:118)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.acceleo.query.parser.AstValidator.validate(AstValidator.java:871)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseQuery(TemplateValidator.java:309)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseQuery(TemplateValidator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:110)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseTemplate(TemplateValidator.java:151)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseTemplate(TemplateValidator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:149)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseDocumentTemplate(TemplateValidator.java:136)
	at org.obeonetwork.m2doc.generator.TemplateValidator.caseDocumentTemplate(TemplateValidator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:192)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.TemplateValidator.validate(TemplateValidator.java:130)
	at org.obeonetwork.m2doc.generator.TemplateValidator.validate(TemplateValidator.java:108)
	at org.obeonetwork.m2doc.generator.TemplateValidator.validate(TemplateValidator.java:92)
	at org.obeonetwork.m2doc.api.GenconfToDocumentGenerator.validate(GenconfToDocumentGenerator.java:262)
	at org.obeonetwork.m2doc.api.GenconfToDocumentGenerator.validate(GenconfToDocumentGenerator.java:236)
	at org.obeonetwork.m2doc.ui.command.ValidateHandler.execute(ValidateHandler.java:65)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 37 more
Caused by: org.eclipse.acceleo.query.runtime.AcceleoQueryValidationException: An internal error occured during validation of a query
	at org.eclipse.acceleo.query.runtime.impl.ValidationServices.callType(ValidationServices.java:180)
	at org.eclipse.acceleo.query.runtime.impl.ValidationServices.callOrApplyTypes(ValidationServices.java:218)
	... 70 more
Caused by: java.lang.IllegalStateException: don't know what to do with null
	at org.eclipse.acceleo.query.services.EObjectServices$EObjectFeatureAccess.featureAccessTypes(EObjectServices.java:233)
	at org.eclipse.acceleo.query.services.EObjectServices$EObjectFeatureAccess.getType(EObjectServices.java:198)
	at org.eclipse.acceleo.query.runtime.impl.ValidationServices.callType(ValidationServices.java:151)
	... 71 more
[family.zip](https://github.com/ObeoNetwork/M2Doc/files/463977/family.zip)
